# 指定应用访问的上下文及端口
server:
  context-path: /middleware
  port: 8087

#logging 日志配置
logging:
  path: /srv/dubbo/middleware/logs
  file: middleware
  level:
    org.springframework: INFO
    com.fasterxml.jackson: INFO
    com.debug.middleware: DEBUG

#json 日期格式化
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/db_middleware?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jmx:
    enabled: true

mq.env: local

mq:
  basic:
    info:
      queue.name: ${mq.env}.middleware.mq.basic.info.queue
      exchange.name: ${mq.env}.middleware.mq.basic.info.exchange
      routing.key.name: ${mq.env}.middleware.mq.basic.info.routing.key
  object:
    info:
      queue.name: ${mq.env}.middleware.mq.object.info.queue
      exchange.name: ${mq.env}.middleware.mq.object.info.exchange
      routing.key.name: ${mq.env}.middleware.mq.object.info.routing.key

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  check-config-location: true
  mapper-locations:
    - classpath:mapping/*.xml
