package com.debug.middleware.model.dao;

import com.debug.middleware.model.entity.RedDetail;

public interface RedDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int insert(RedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int insertSelective(RedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    RedDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int updateByPrimaryKeySelective(RedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int updateByPrimaryKey(RedDetail record);
}