package com.debug.middleware.model.dao;

import com.debug.middleware.model.entity.RedRecord;

public interface RedRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int insert(RedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int insertSelective(RedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    RedRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int updateByPrimaryKeySelective(RedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int updateByPrimaryKey(RedRecord record);
}