package com.debug.middleware.model.dao;

import com.debug.middleware.model.entity.RedRobRecord;

public interface RedRobRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int insert(RedRobRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int insertSelective(RedRobRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    RedRobRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int updateByPrimaryKeySelective(RedRobRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbggenerated Sun May 17 00:20:15 CST 2020
     */
    int updateByPrimaryKey(RedRobRecord record);
}