package com.debug.middleware.model.dao;

import com.debug.middleware.model.entity.UserOrder;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Thu May 21 14:31:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Thu May 21 14:31:55 CST 2020
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Thu May 21 14:31:55 CST 2020
     */
    int insertSelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Thu May 21 14:31:55 CST 2020
     */
    UserOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Thu May 21 14:31:55 CST 2020
     */
    int updateByPrimaryKeySelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Thu May 21 14:31:55 CST 2020
     */
    int updateByPrimaryKey(UserOrder record);

    UserOrder selectByIdAndStatus(@Param("id") Integer id, @Param("status") Integer status);
}