package com.debug.middleware.model.dao;

import com.debug.middleware.model.entity.UserAccount;
import org.apache.ibatis.annotations.Param;

public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    UserAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    int updateByPrimaryKey(UserAccount record);


    UserAccount selectByUserId(@Param("userId") Integer userId);


    int updateAmount(@Param("money") Double money, @Param("id") Integer id);


    int updateAmountByVersion(@Param("money") Double money,
                              @Param("id") Integer id,
                              @Param("version") Integer version);

    //根据用户id查询记录-for update方式
    UserAccount selectByUserIdLock(@Param("userId") Integer userId);

    //更新账户金额-悲观锁的方式
    int updateAmountLock(@Param("money") Double money,@Param("id") Integer id);


}