package com.debug.middleware.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccountRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_record.id
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_record.account_id
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_record.money
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_record.create_time
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_record.id
     *
     * @return the value of user_account_record.id
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_record.id
     *
     * @param id the value for user_account_record.id
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_record.account_id
     *
     * @return the value of user_account_record.account_id
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_record.account_id
     *
     * @param accountId the value for user_account_record.account_id
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_record.money
     *
     * @return the value of user_account_record.money
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_record.money
     *
     * @param money the value for user_account_record.money
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_record.create_time
     *
     * @return the value of user_account_record.create_time
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_record.create_time
     *
     * @param createTime the value for user_account_record.create_time
     *
     * @mbggenerated Fri May 22 13:53:40 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}